/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.DaoRegistroUsuarios;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Leo_b
 */
public class FormGestionUsuarios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormGestionUsuarios.class.getName());

    /**
     * Creates new form FormGestionUsuarios
     */
    public FormGestionUsuarios() {
        // TblUsuarios.setDefaultEditor(Object.class, null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TfNombre = new javax.swing.JTextField();
        CbRol = new javax.swing.JComboBox<>();
        PfPass = new javax.swing.JPasswordField();
        PfPassCheck = new javax.swing.JPasswordField();
        BtnAgregarUsuario = new javax.swing.JButton();
        BtnModificarUsuario = new javax.swing.JButton();
        BtnEliminarUsuario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        TblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblUsuarios);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Rol:");

        jLabel3.setText("Contraseña:");

        jLabel4.setText("Confirmar Contraseña:");

        CbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione", "Reporte", "Inventario", "Admin" }));

        PfPass.addActionListener(this::PfPassActionPerformed);

        BtnAgregarUsuario.setText("Agregar");
        BtnAgregarUsuario.addActionListener(this::BtnAgregarUsuarioActionPerformed);

        BtnModificarUsuario.setText("Modificar");
        BtnModificarUsuario.addActionListener(this::BtnModificarUsuarioActionPerformed);

        BtnEliminarUsuario.setText("Eliminar");
        BtnEliminarUsuario.addActionListener(this::BtnEliminarUsuarioActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Gestión de usuarios:");

        jLabel6.setText("Agregue o edite los siguientes campos:");

        jLabel7.setText("(Seleccione usuario de la lista para modificar o eliminar)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(58, 58, 58))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PfPass)
                        .addComponent(CbRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TfNombre)
                        .addComponent(PfPassCheck))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAgregarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnModificarUsuario))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnEliminarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(CbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PfPassCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnAgregarUsuario)
                        .addComponent(BtnModificarUsuario))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnEliminarUsuario)
                        .addComponent(jLabel7)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarUsuarioActionPerformed

    private void BtnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarUsuarioActionPerformed

    private void PfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PfPassActionPerformed

    private void BtnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarUsuarioActionPerformed
        //Capturar:
        String nombre = TfNombre.getText().trim().toLowerCase();
        String rol = CbRol.getSelectedItem().toString().trim().toUpperCase();
        String pass = PfPass.getText().trim();
        String passCheck = PfPassCheck.getText();

        if (nombre.length() < 2 || nombre.length() > 20) {
            String errorMessage = "Debe agregar un nombre válido. Largo mín: 2 | máx: 20";
            System.out.println(errorMessage);
            JOptionPane.showMessageDialog(null, errorMessage, "Error", 0);
        } else if (rol.equalsIgnoreCase("seleccione")) {
            String errorMessage = "Debe seleccionar un rol de usuario";
            System.out.println(errorMessage);
            JOptionPane.showMessageDialog(null, errorMessage, "Error", 0);
        } else if (pass.length() < 8 || pass.length() > 12 || !pass.matches(".*[a-z].*") || !pass.matches(".*[A-Z].*") || !pass.matches(".*\\d.*") || !pass.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()_+\\-=?¿¡!.,;:]).{6,}$")) {
            String errorMessage = "La contraseña debe cumplir:\n*Largo = mín: 8 | máx: 12\n*Al menos 1 minúscula\n*Al menos 1 mayúscula\n*Al menos 1 caracter especial";
            System.out.println(errorMessage);
            JOptionPane.showMessageDialog(null, errorMessage, "Error", 0);
        } else if (!pass.equals(passCheck)) {
            String errorMessage = "La contraseña debe coincidir en ambos campos.";
            System.out.println(errorMessage);
            JOptionPane.showMessageDialog(null, errorMessage, "Error", 0);
        } else {
            try {
                Usuario u = new Usuario(nombre, pass, rol);
                DaoRegistroUsuarios dru = new DaoRegistroUsuarios();
                if (dru.agregarUsuario(u)) {
                    String resultMessage = "Usuario " + u.getNombre() + " agregado exitósamente en sistema.";
                    System.out.println("FormGestionUsuarios:" + resultMessage);
                    JOptionPane.showMessageDialog(null, resultMessage, "Registro de nuevo usuario", JOptionPane.INFORMATION_MESSAGE);

                }
            } catch (Exception e) {
                String errorMessage = "Error al agregar usuario en sistema.";
                System.out.println("FormGestionUsuarios:" + errorMessage);
                JOptionPane.showMessageDialog(null, errorMessage, "Error", 0);
            }
        }
    }//GEN-LAST:event_BtnAgregarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormGestionUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarUsuario;
    private javax.swing.JButton BtnEliminarUsuario;
    private javax.swing.JButton BtnModificarUsuario;
    private javax.swing.JComboBox<String> CbRol;
    private javax.swing.JPasswordField PfPass;
    private javax.swing.JPasswordField PfPassCheck;
    private javax.swing.JTable TblUsuarios;
    private javax.swing.JTextField TfNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
