/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.DaoRegistroUsuarios;
import Modelo.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.Normalizer;

/**
 *
 * @author Leo_b
 */
public class FormGestionPerfilPersonal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormGestionPerfilPersonal.class.getName());

    /**
     * Creates new form FormGestionUsuarios
     */
    public FormGestionPerfilPersonal() {
        initComponents();

        BtnModificarUsuario.setEnabled(false);

    }

    public void limpiarCampos() {

        PfPass.setText("");
        PfPassCheck.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PfPass = new javax.swing.JPasswordField();
        PfPassCheck = new javax.swing.JPasswordField();
        BtnModificarUsuario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LbID = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LbRol = new javax.swing.JLabel();

        jLabel9.setText("Nueva contraseña:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nombre:");

        jLabel3.setText("Nueva contraseña:");

        jLabel4.setText("Confirmar Contraseña:");

        PfPass.addActionListener(this::PfPassActionPerformed);

        BtnModificarUsuario.setText("Modificar");
        BtnModificarUsuario.addActionListener(this::BtnModificarUsuarioActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Gestión de perfil:");

        jLabel8.setText("ID: ");

        LbID.setText("desconocido");

        LbNombre.setText("desconocido");

        jLabel11.setText("Rol:");

        LbRol.setText("desconocido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(BtnModificarUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PfPass, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PfPassCheck, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LbID, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                            .addComponent(LbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LbID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LbNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(LbRol))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PfPassCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnModificarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarUsuarioActionPerformed
        //Capturar:
        int id = Integer.parseInt(LbID.getText());

        String nombre = LbNombre.getText();
        String rol = LbRol.getText();
        String pass = PfPass.getText().trim();
        String passCheck = PfPassCheck.getText();

        if (pass.length() < 8 || pass.length() > 12 || !pass.matches(".*[a-z].*") || !pass.matches(".*[A-Z].*") || !pass.matches(".*\\d.*") || !pass.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*()_+\\-=?¿¡!.,;:]).{6,}$")) {
            String errorMessage = "La contraseña debe cumplir:\n*Largo = mín: 8 | máx: 12\n*Al menos 1 minúscula\n*Al menos 1 mayúscula\n*Al menos 1 caracter especial";
            System.out.println(errorMessage);
            JOptionPane.showMessageDialog(null, errorMessage, "Error", 0);
        } else if (!pass.equals(passCheck)) {
            String errorMessage = "La contraseña debe coincidir en ambos campos.";
            System.out.println(errorMessage);
            JOptionPane.showMessageDialog(null, errorMessage, "Error", 0);
        } else {
            try {
                Usuario um = new Usuario(nombre, pass, rol, id);
                DaoRegistroUsuarios dru = new DaoRegistroUsuarios();
                if (dru.modificarUsuario(um)) {
                    String resultMessage = "Usuario " + um.getNombre() + " modificado exitósamente en sistema.";
                    System.out.println("FormGestionUsuarios:" + resultMessage);
                    JOptionPane.showMessageDialog(null, resultMessage, "Modificación de usuario", JOptionPane.INFORMATION_MESSAGE);

                }
            } catch (Exception e) {
                String errorMessage = "Error al intentar modificar usuario en sistema.";
                System.out.println("FormGestionUsuarios:" + errorMessage);
                JOptionPane.showMessageDialog(null, errorMessage, "Error", 0);
            }
        }
    }//GEN-LAST:event_BtnModificarUsuarioActionPerformed

    private void PfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PfPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormGestionPerfilPersonal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModificarUsuario;
    private javax.swing.JLabel LbID;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JLabel LbRol;
    private javax.swing.JPasswordField PfPass;
    private javax.swing.JPasswordField PfPassCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
